@echo off && call cmdex_pre_run.bat

set REQUESTED_DIRECTORY="%*"
set REQUESTED_DIRECTORY_WRAPPED="%REQUESTED_DIRECTORY:"=%"

if not exist %REQUESTED_DIRECTORY_WRAPPED% (mkdir %REQUESTED_DIRECTORY_WRAPPED%)

chdir /d %REQUESTED_DIRECTORY_WRAPPED%


